app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/amigoscode
      username: amigoscode
      password: "pass"
      pool-size: 30
spring:
  datasource.type: com.zaxxer.hikari.HikariDataSource

server:
  error:
    include-binding-errors: always
    include-message: always


